### ISSUE TITLE
Allow multiple data generators for each parameter

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#19]
So far, RESTest only allows to configure one data generator for each parameter. However, it would be interesting to have multiple data generators. This would also allow the generation of different types of nominal and faulty test cases. Data generators could also be tagged with information on whether they create valid or invalid data. In the following lines, an example for the Bikewise API is provided. Two valid data generators are created (RandomNumber within limits and RandomBoundaryNumber within limits) as well as two invalid ones (RandomBoundaryNumber out of limits and RandomBoolean).

```yaml
- operationId: GET--version-incidents---format-
  method: get
  testParameters:
  - name: page
    weight: 0.5
    generators:
    - type: RandomNumber
      valid: true
      genParameters:
      - name: type
        values:
        - integer
      - name: min
        values:
        - 1
      - name: max
        values:
        - 100
    - type: RandomBoundaryNumber
      valid: true
      genParameters:
      - name: type
        values:
        - integer
      - name: min
        values:
        - 2
      - name: max
        values:
        - 99
      - name: delta
        values:
        - 1
    - type: RandomBoundaryNumber
      valid: false
      genParameters:
      - name: type
        values:
        - integer
      - name: min
        values:
        - -1
      - name: max
        values:
        - 102
      - name: delta
        values:
        - 1
    - type: RandomBoolean
      valid: false
      genParameters: []
```
