### ISSUE TITLE
Option to select multiple elements with RandomInputValue

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#32]
This feature is very useful for those parameters that accept a comma-separated list of values. The YAML would look something like this:

```yaml
generator:
  type: RandomInputValue
  genParameters:
  - name: csv
    values:
    - src/main/resources/TestData/MarvelEventIDs.csv
  - name: minValues
    values:
    - 1
  - name: maxValues
    values:
    - 5
  - name: separator
    values:
    - ","
```

Classes to modify (off the top of my head): RandomInputValue, TestDataGeneratorFactory.
